export const ADD_TO_CART = 'ADD_TO_CART';
export const APPLY_DISCOUNT = 'APPLY_DISCOUNT';
export const FETCH_PACKAGES_REQUEST = 'FETCH_PACKAGES_REQUEST';
export const FETCH_PACKAGES_SUCCESS = 'FETCH_PACKAGES_SUCCESS';
export const FETCH_PACKAGES_FAILURE = 'FETCH_PACKAGES_FAILURE';
export const SHOW_PACKAGE_DETAILS = 'SHOW_PACKAGE_DETAILS';
